name: Autograding

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: StarterProject

    - name: Build
      run: dotnet build --no-restore
      working-directory: StarterProject

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
      working-directory: StarterProject
